version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=Temp1925

    redis:
        image: 'redis:latest'
    
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - ./server:/app
        environment:
            - CHOKIDAR_USEPOLLING=true      
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=Temp1925
            - PGPORT=5432

    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./app
        volumes:
            - ./app:/app
        environment:
            - CHOKIDAR_USEPOLLING=true      
            - REDIS_HOST=redis
            - REDIS_PORT=6379

            
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - ./worker:/app
        environment:
            - CHOKIDAR_USEPOLLING=true      
            - REDIS_HOST=redis
            - REDIS_PORT=6379
                 

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on:
            - api
            - client
        ports:
            - '3050:80'

                      